### ISSUE TITLE
Training a Text-Line detector but not getting good results

### ISSUE THREAD

**Issue by seekingdeep** [monniert/docExtractor#11]
@monniert 
I trained a text-line detector model, the accuracy seemed high, but when i tested, the results were very bad. i even tried training at different image sizes, but still the results were not good.
My Guess is that the ground truth should not be all in the same color "cyan", you might need to choose 2 colors, example: first line "cyan", then second line "red", then 3rd line "cyan", then 4th line "red", etc..... This might help in separating close regions.

possible solution:
![image](https://user-images.githubusercontent.com/71519088/105577276-8482cf00-5d89-11eb-87bb-4164f3820196.png)

Example:
![19699_annotated](https://user-images.githubusercontent.com/71519088/105577084-77191500-5d88-11eb-8f43-44c9da8b16cf.jpg)

Groundtruth:
![19699_seg](https://user-images.githubusercontent.com/71519088/105577095-839d6d80-5d88-11eb-8655-4fe56f8fcf6e.png)

Original image:
![19699](https://user-images.githubusercontent.com/71519088/105577100-8e580280-5d88-11eb-92a4-61a267b7bcd3.jpg)

**Comment by monniert** [comment]
Again, why do you say results are bad in this case? Mistakes seem to only occur for the footnotes. Three things you can try to prevent text lines merging and improve results:

- clean ground truth: it seems you have merged line labels in your GT, so you should expect predicted lines to be merged as well, you first need to clean it to prevent such behaviour
- use x-height label instead of bounding box label (check [here](https://en.wikipedia.org/wiki/X-height)): predicted lines should be thinner and more accurate
- use border label to force gaps between lines (check the paper for explanation and ablation experiments)

**Comment by monniert** [comment]
@seekingdeep closing the issue, please reopen if necessary

**Comment by seekingdeep** [comment]
you are right, this most likely is caused because i didn't use x-height+border in the annotation for training.
instead i used bounding-box for entire text-line which resulted in text-line to be merging with another.
